language: python
os: linux
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

cache:
  pip: true

install:
  - pip install -e .[tests]

script: coverage run -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
